server:
  port: 2001

spring:
  application:
    name: account-server
  datasource:
    # 配置数据源类型
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank1?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: lyl512240816
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j
  aop:
    auto=true:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

mybatis:
  mapper-locations: classpath*:**/mapper/*/*Mapper.xml

#如果服务部署了几个节点， 负载均衡算法最好使用 hmily自带, 这样 try, confirm, cancel 调用会落在同一个节点 充分利用了缓存，提搞了效率
hmily:
  ribbon:
    rule:
      enabled: true

#Ribbon的负载均衡策略
ribbon:
  NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule
  ConnectTimeout: 600 # 设置连接超时时间 default 2000
  ReadTimeout: 6000    # 设置读取超时时间  default 5000
  OkToRetryOnAllOperations: fasle # 对所有操作请求都进行重试  default false
  MaxAutoRetriesNextServer: 0    # 切换实例的重试次数  default 1
  MaxAutoRetries: 0     # 对当前实例的重试次数 default 0
feign:
  hystrix:
    enabled : false # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000  # 设置熔断超时时间  default 1000
        timeout:
          enabled: true # 打开超时熔断功能 default true

